# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'httparty', '~> 0.21.0'
gem 'minitest', '>= 5.0.0'
gem 'pry', '~> 0.12.2'
gem 'pry-byebug'
gem 'rgl'
# gem "rails"
